[package]
name = "polymarketwatcher"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
polymarket-rs-client = "0.1.1"
reqwest = "0.12.15"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.34", features = ["full"] }
